### ISSUE TITLE
Question about usage of loadFrozenModel() in tfjs-mnist/src/index.js and others

### ISSUE THREAD

**Issue by hideya** [akimach/tensorflow17-sampler#1]
Thanks for sharing the nice examples, which are very educational!

I'm a beginner of tfjs, and got a question about the usage of `loadFrozenModel()` in `tfjs-mnist/src/index.js`:
https://github.com/akimach/tensorflow17-sampler/blob/80e8ae79904981a444b096016a01aa8fde06d85c/tfjs-mnist/src/index.js#L11

It looks to me that `loadFrozenModel()` is invoked always when the inference button is clicked.
I'm wondering why it couldn't be just once...?
Could you tell me why the code is written in the current way?

There are a few more questions...
- I'm wondering why Line 1 (the following) is included.  I think the code works without it as `tfjs-core` is imported.
https://github.com/akimach/tensorflow17-sampler/blob/80e8ae79904981a444b096016a01aa8fde06d85c/tfjs-mnist/src/index.js#L1
- Checking google's example, they use `tf.tidy()` to fee up GPU memory automatically when tensor operation is taken place, for example:
https://github.com/tensorflow/tfjs-examples/blob/bf51024bd04fa6197b410db10e5210d4604aef43/mnist/index.js#L114-L122
I'm wondering whether it is needed for the following case...?
https://github.com/akimach/tensorflow17-sampler/blob/80e8ae79904981a444b096016a01aa8fde06d85c/tfjs-mnist/src/index.js#L12-L14

Any input will be much appreciated!

**Comment by akimach** [comment]
Thank you for your good comment! I fixed based on your comment.

**Comment by hideya** [comment]
Wow, it was quick!  The updated code looks good to me!
Thanks for reading the comments and sharing the updates.

I have additional comments, but they are minor.  I'm closing this issue as fixed.

- I'm still wondering wether the following line is really needed...?
https://github.com/akimach/tensorflow17-sampler/blob/44fc7556a0939e87c4d95e43b68909e05115d00b/tfjs-mnist/src/predictor.js#L1
- possible typo: `preditor`
https://github.com/akimach/tensorflow17-sampler/blob/44fc7556a0939e87c4d95e43b68909e05115d00b/tfjs-mnist/src/index.js#L5

**Comment by akimach** [comment]
@hideya 

> import * as tf from '@tensorflow/tfjs'; 

I imported tf to use `tf.tensor2d`.

Thanks!

**Comment by hideya** [comment]
Ah!  That's good to know!  Thank you for your comment back!
